--SALES ORDER--
----------comment------
SELECT T1.lOGINSTANC,dbo.ObType(t1.ObjType) AS ObjectType,T1.TaxDate,T1.DocEntry,'' AS FieldName,
''  AS OLDVALUE,
'' AS NEWVALUE,
'ADD' AS INSTANCE,
(SELECT U_NAME FROM OUSR WHERE OUSR.INTERNAL_K = T1.UserSign) AS USERS
FROM ORDR T1
WHERE ISNULL((SELECT TOP 1 ADOC.Comments FROM ADOC WHERE ADOC.DocEntry = T1.DOCNUM),T1.COMMENTS) IS NOT NULL

UNION ALL

SELECT T0.lOGINSTANC, dbo.ObType(t0.ObjType) AS ObjectType,T0.TaxDate,T0.DocEntry,'REMARKS' AS FieldName,
(SELECT ADOC.Comments FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc AND ADOC.ObjType = T0.ObjType ) AS OLDVALUE,
 ISNULL((SELECT ADOC.Comments FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),T1.Comments) AS NEWVALUE,
 'UPDATE' AS INSTANCE,
(SELECT U_NAME FROM OUSR WHERE OUSR.INTERNAL_K = T0.UserSign) AS USERS
FROM ORDR T1
JOIN ADOC T0 ON T1.DocNum = T0.DocEntry
WHERE ISNULL((SELECT ADOC.Comments FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),T1.Comments) IS NOT NULL
AND (SELECT ADOC.Comments FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc AND ADOC.ObjType = T0.ObjType ) <>  ISNULL((SELECT ADOC.Comments FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),T1.Comments) 
-----------comment-------------

UNION ALL

----------CONTACT PERSON------

SELECT T0.lOGINSTANC, dbo.ObType(t0.ObjType) AS ObjectType,T0.TaxDate,T0.DocEntry,'CONTACT PERSON' AS FieldName,
(SELECT CAST(ADOC.CNTCTCODE AS VARCHAR) FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc AND ADOC.ObjType = T0.ObjType ) AS OLDVALUE,
 ISNULL((SELECT CAST(ADOC.CNTCTCODE AS VARCHAR) FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),T1.CNTCTCODE) AS NEWVALUE,
 'UPDATE' AS INSTANCE,
(SELECT U_NAME FROM OUSR WHERE OUSR.INTERNAL_K = T0.UserSign) AS USERS
FROM ORDR T1
JOIN ADOC T0 ON T1.DocNum = T0.DocEntry
WHERE ISNULL((SELECT CAST(ADOC.CNTCTCODE AS VARCHAR) FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),T1.CNTCTCODE) != '0'
AND (SELECT CAST(ADOC.CNTCTCODE AS VARCHAR) FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc AND ADOC.ObjType = T0.ObjType ) <> ISNULL((SELECT CAST(ADOC.CNTCTCODE AS VARCHAR) FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),T1.CNTCTCODE)
-----------CONTACT PERSON-------------
UNION ALL

----------CUSTOMER REF. NO------

SELECT T0.lOGINSTANC, dbo.ObType(t0.ObjType) AS ObjectType,T0.TaxDate,T0.DocEntry,'CUSTOMER REF. NO' AS FieldName,
(SELECT CAST(ADOC.NUMATCARD AS VARCHAR) FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc AND ADOC.ObjType = T0.ObjType ) AS OLDVALUE,
 ISNULL((SELECT CAST(ADOC.NUMATCARD AS VARCHAR) FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),T1.NUMATCARD) AS NEWVALUE,
 'UPDATE' AS INSTANCE,
(SELECT U_NAME FROM OUSR WHERE OUSR.INTERNAL_K = T0.UserSign) AS USERS
FROM ORDR T1
JOIN ADOC T0 ON T1.DocNum = T0.DocEntry
WHERE ISNULL((SELECT CAST(ADOC.NUMATCARD AS VARCHAR) FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),T1.NUMATCARD) != '0'
AND (SELECT CAST(ADOC.NUMATCARD AS VARCHAR) FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc AND ADOC.ObjType = T0.ObjType ) <> ISNULL((SELECT CAST(ADOC.NUMATCARD AS VARCHAR) FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),T1.NUMATCARD)
-----------CUSTOMER REF. NO-------------

UNION ALL

----------CUSTOMER NAME------

SELECT T0.lOGINSTANC, dbo.ObType(t0.ObjType) AS ObjectType,T0.TaxDate,T0.DocEntry,'CUSTOMER REF. NO' AS FieldName,
(SELECT CAST(ADOC.U_CUSTOMER AS VARCHAR) FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc AND ADOC.ObjType = T0.ObjType ) AS OLDVALUE,
 ISNULL((SELECT CAST(ADOC.U_CUSTOMER AS VARCHAR) FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),T1.U_CUSTOMER) AS NEWVALUE,
 'UPDATE' AS INSTANCE,
(SELECT U_NAME FROM OUSR WHERE OUSR.INTERNAL_K = T0.UserSign) AS USERS
FROM ORDR T1
JOIN ADOC T0 ON T1.DocNum = T0.DocEntry
WHERE ISNULL((SELECT CAST(ADOC.U_CUSTOMER AS VARCHAR) FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),T1.U_CUSTOMER) != '0'
AND (SELECT CAST(ADOC.U_CUSTOMER AS VARCHAR) FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc AND ADOC.ObjType = T0.ObjType ) <> ISNULL((SELECT CAST(ADOC.U_CUSTOMER AS VARCHAR) FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),T1.U_CUSTOMER)
-----------CUSTOMER NAME-------------

UNION ALL

----------POSTING DATE------

SELECT T0.lOGINSTANC, dbo.ObType(t0.ObjType) AS ObjectType,T0.TaxDate,T0.DocEntry,'POSTING DATE' AS FieldName,
(SELECT FORMAT((ADOC.DOCDATE),'yyyy-MM-dd') FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc AND ADOC.ObjType = T0.ObjType ) AS OLDVALUE,
 ISNULL((SELECT FORMAT((ADOC.DOCDATE),'yyyy-MM-dd') FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),FORMAT((T1.DOCDATE),'yyyy-MM-dd')) AS NEWVALUE,
 'UPDATE' AS INSTANCE,
(SELECT U_NAME FROM OUSR WHERE OUSR.INTERNAL_K = T0.UserSign) AS USERS
FROM ORDR T1
JOIN ADOC T0 ON T1.DocNum = T0.DocEntry
WHERE ISNULL((SELECT FORMAT((ADOC.DOCDATE),'yyyy-MM-dd') FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),FORMAT((T1.DOCDATE),'yyyy-MM-dd')) != '0'
AND (SELECT FORMAT((ADOC.DOCDATE),'yyyy-MM-dd') FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc AND ADOC.ObjType = T0.ObjType ) <> ISNULL((SELECT FORMAT((ADOC.DOCDATE),'yyyy-MM-dd') FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),FORMAT((T1.DOCDATE),'yyyy-MM-dd'))
-----------POSTING DATE-------------

UNION ALL

----------DELIVERY DATE------

SELECT T0.lOGINSTANC, dbo.ObType(t0.ObjType) AS ObjectType,T0.TaxDate,T0.DocEntry,'DELIVERY DATE' AS FieldName,
(SELECT FORMAT((ADOC.DOCDUEDATE),'yyyy-MM-dd') FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc AND ADOC.ObjType = T0.ObjType ) AS OLDVALUE,
 ISNULL((SELECT FORMAT((ADOC.DOCDUEDATE),'yyyy-MM-dd') FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),FORMAT((T1.DOCDUEDATE),'yyyy-MM-dd')) AS NEWVALUE,
 'UPDATE' AS INSTANCE,
(SELECT U_NAME FROM OUSR WHERE OUSR.INTERNAL_K = T0.UserSign) AS USERS
FROM ORDR T1
JOIN ADOC T0 ON T1.DocNum = T0.DocEntry
WHERE ISNULL((SELECT FORMAT((ADOC.DOCDUEDATE),'yyyy-MM-dd') FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),FORMAT((T1.DOCDUEDATE),'yyyy-MM-dd')) != '0'
AND (SELECT FORMAT((ADOC.DOCDUEDATE),'yyyy-MM-dd') FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc AND ADOC.ObjType = T0.ObjType ) <> ISNULL((SELECT FORMAT((ADOC.DOCDUEDATE),'yyyy-MM-dd') FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),FORMAT((T1.DOCDUEDATE),'yyyy-MM-dd'))
-----------DELIVERY DATE-------------

UNION ALL

----------DOCUMENT DATE------

SELECT T0.lOGINSTANC, dbo.ObType(t0.ObjType) AS ObjectType,T0.TaxDate,T0.DocEntry,'DOCUMENT DATE' AS FieldName,
(SELECT FORMAT((ADOC.TAXDATE),'yyyy-MM-dd') FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc AND ADOC.ObjType = T0.ObjType ) AS OLDVALUE,
 ISNULL((SELECT FORMAT((ADOC.TAXDATE),'yyyy-MM-dd') FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),FORMAT((T1.TAXDATE),'yyyy-MM-dd')) AS NEWVALUE,
 'UPDATE' AS INSTANCE,
(SELECT U_NAME FROM OUSR WHERE OUSR.INTERNAL_K = T0.UserSign) AS USERS
FROM ORDR T1
JOIN ADOC T0 ON T1.DocNum = T0.DocEntry
WHERE ISNULL((SELECT FORMAT((ADOC.TAXDATE),'yyyy-MM-dd') FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),FORMAT((T1.TAXDATE),'yyyy-MM-dd')) != '0'
AND (SELECT FORMAT((ADOC.TAXDATE),'yyyy-MM-dd') FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc AND ADOC.ObjType = T0.ObjType ) <> ISNULL((SELECT FORMAT((ADOC.TAXDATE),'yyyy-MM-dd') FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1 AND ADOC.ObjType = T0.ObjType),FORMAT((T1.TAXDATE),'yyyy-MM-dd'))
-----------DOCUMENT DATE-------------





ORDER BY DOCENTRY,LogInstanc ASC
--SALES ORDER--

















-- SELECT T0.DocEntry,
-- -- ISNULL((SELECT ADOC.Comments FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc -1),T1.Comments) AS SOURCE,
-- (SELECT ADOC.Comments FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc -1) AS SOURCE,
-- (SELECT ADOC.Comments FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc ) AS OLDVALUE,
--  ISNULL((SELECT ADOC.Comments FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1),T1.Comments) AS NEWVALUE,
-- T0.LogInstanc -1 AS OLDLOGINSTANC,
-- T0.lOGINSTANC, 
-- ISNULL((SELECT ADOC.lOGINSTANC FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry AND ADOC.LogInstanc = T0.LogInstanc+1),(SELECT MAX(ADOC.LogInstanc) FROM ADOC WHERE ADOC.DocEntry = T0.DocEntry)+1) AS NEWLOGINSTANC, 
-- T1.Comments
-- FROM ORDR T1
-- LEFT JOIN ADOC T0 ON T1.DocNum = T0.DocEntry
-- WHERE T1.DocEntry = 26

